-- CreateTable
CREATE TABLE "gameData" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "pId1" STRING NOT NULL,
    "pId2" STRING NOT NULL,
    "mode" STRING NOT NULL,

    CONSTRAINT "gameData_pkey" PRIMARY KEY ("id")
);
